version: '3.3'
services:

  mysql:
    build: ./mysql
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
